package com.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DATA".
 */
public class Data {

    private Long id;
    /** Not-null value. */
    private String ShopName;
    private String image;
    private String name;
    private Integer price;
    private String number;

    public Data() {
    }

    public Data(Long id) {
        this.id = id;
    }

    public Data(Long id, String ShopName, String image, String name, Integer price, String number) {
        this.id = id;
        this.ShopName = ShopName;
        this.image = image;
        this.name = name;
        this.price = price;
        this.number = number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getShopName() {
        return ShopName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShopName(String ShopName) {
        this.ShopName = ShopName;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

}
